/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
const useEntityForm = () => {
  const setTaxIdType = (): any => {};
  const setAccreditation = (): any => {};
  const setControlPersonExempt = (): any => {};
  const data: any = {};
  const setEntityType = (param1: any): any => {};
  const setAccountName = (param1: any): any => {};
  const setTaxId = (param1: any): any => {};
  const setTaxNumber = (param1: any): any => {};
  const setForeignInvestor = (param1: any): any => {};
  const setAccredition = (param1: any): any => {};
  const setExemptReason = (param1: any): any => {};

  const fns: any = {
    setEntityType,
    setAccountName,
    setTaxId,
    setTaxNumber,
    setForeignInvestor,
    setAccredition,
    setExemptReason, setTaxIdType, setAccreditation, setControlPersonExempt
  };

  return { data, fns };
};

export default useEntityForm;
